#!/bin/bash

echo "Loading histctrl"

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s cmdhist  
shopt -s cdspell

history() {
  _bash_history_sync
  builtin history "$@"
}

_bash_history_sync() {
  builtin history -a         #1
  #HISTFILESIZE=$HISTSIZE     #2
  builtin history -c         #3
  builtin history -r         #4
}

export HISTCONTROL=ignorespace:ignoredups
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export HISTTIMEFORMAT='%Y-%m-%d %H:%M:%S - '
if [ "$(uname)" != "Darwin" ]; then
    export HISTFILE=${HOME}/.bash_h_keep
fi

export PROMPT_COMMAND=_bash_history_sync


