#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

BASH_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

if [ -f /etc/bashrc ]; then
    . /etc/bashrc   # --> Read /etc/bashrc, if present.
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
        debian_chroot=$(cat /etc/debian_chroot)
fi

if which tput > /dev/null 2>&1 && [[ $(tput -T$TERM colors) -ge 8 ]]; then
    #if  [[ "$(hostname)" =~ "-server" ]]; then
    if [ "$(id -u)" == "0" ]; then
	     export PS1='\n\[\e[1;34m\]\w\[\e[0;0m\]\n\[\e[1;31m\]\u@\h\[\e[0;0m\] \$ '
    else
	     export PS1="\n\[\e[1;34m\]\w \[\033[36m\]\$(parse_git_branch)\[\e[0;0m\]\n\[\e[01;32m\]\u@\h\[\e[0;0m\] \$ "
   fi
else
    export PS1='\n\w\n\u@\h \$ '
fi

echo "Loading bashrc"

if [ -f ${HOME}/.bash_custom ]; then
    . ${HOME}/.bash_custom
fi

if [ -f ${BASH_DIR}/bash_histctrl ]; then
    . ${BASH_DIR}/bash_histctrl
fi

if [ -f ${BASH_DIR}/bash_exports ]; then
    . ${BASH_DIR}/bash_exports
fi

if [ -f ${BASH_DIR}/bash_completion ]; then
    . ${BASH_DIR}/bash_completion
fi

if [ -f ${BASH_DIR}/bash_aliases ]; then
    . ${BASH_DIR}/bash_aliases
fi

if [ -f ${BASH_DIR}/bash_functions ]; then
    . ${BASH_DIR}/bash_functions
fi


test -r $HOME/.dircolors  && eval $( dircolors -b $HOME/.dircolors )

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/sbin:$PATH"
