#!/bin/bash
echo "Loading exports"

export VISUAL=vim
export EDITOR="$VISUAL"

#Ant

if [ -d /usr/local/apache-ant ]; then
    export ANT_HOME="/usr/local/apache-ant"
    export PATH=${ANT_HOME}/bin:$PATH
fi

# Maven
if [ -d /usr/local/apache-maven ]; then
    export MVN_HOME=/usr/local/apache-maven
    export MAVEN_OPTS="-client  -Xmx4g -Xms512m -Dmaven.test.failure.ignore=false"
    export PATH=${MVN_HOME}/bin:${PATH}
fi

#Gradle
if [ -d /usr/local/gradle ]; then
    export GRADLE_HOME=/usr/local/gradle
    export PATH=${GRADLE_HOME}/bin:${PATH}
fi

#Java
if [ "$(uname)" = "Darwin" ]; then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
    export JDK_HOME=${JAVA_HOME}
    export JAVACMD="$JAVA_HOME/bin/java"
    export PATH=${JAVA_HOME}/bin:$PATH
elif [ -d /usr/local/java ]; then
    unset CLASSPATH; export CLASSPATH
    unset JAVA_HOME; export JAVA_HOME
    unset JDK_HOME; export JDK_HOME

    export JAVA_HOME="/usr/local/java"
    export JDK_HOME=${JAVA_HOME}
    export JAVACMD="$JAVA_HOME/bin/java"
    export PATH=${JAVA_HOME}/bin:$PATH
fi

# golang

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# Home bin
export PATH="${PATH}:${HOME}/bin"
# echo "Set PATH=${PATH}"
if [ -x /usr/share/source-highlight/src-hilite-lesspipe.sh ]; then
    export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
fi

export LESS=' -R '

## clean up the PATH
export PATH="$(printf "%s" "${PATH}" | /usr/bin/awk -v RS=: -v ORS=: '!($0 in a) {a[$0]; print}')"
